### ISSUE TITLE
Could not process argument extension-googleplayservices-lib

### ISSUE THREAD

**Issue by smks** [SempaiGames/extension-multigames#2]
Could not process argument extension-googleplayservices-lib

BUILD FAILED
C:\Development\Android SDK\tools\ant\build.xml:573: com.android.io.StreamException: java.io.FileNotFoundException: C:\Users\Me\Desktop\Game\export\android\bin\deps\google-play-services_lib\AndroidManifest.xml (The system cannot find the file specified)
    at com.android.io.FileWrapper.getContents(FileWrapper.java:93)
    at com.android.xml.AndroidManifest.getStringValue(AndroidManifest.java:412)
    at com.android.xml.AndroidManifest.getPackage(AndroidManifest.java:148)
    at com.android.ant.ComputeDependencyTask$1.processLibrary(ComputeDependencyTask.java:198)
    at com.android.ant.DependencyHelper$AdvancedLibraryProcessor.processLibrary(DependencyHelper.java:69)
    at com.android.ant.DependencyHelper.processLibraries(DependencyHelper.java:210)
    at com.android.ant.GetLibraryPathTask.execute(GetLibraryPathTask.java:183)
    at com.android.ant.GetLibraryPathTask.execute(GetLibraryPathTask.java:162)
    at com.android.ant.ComputeDependencyTask.execute(ComputeDependencyTask.java:226)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.FileNotFoundException: C:\Users\Shaun Stone\Desktop\RonnieRooster\export\android\bin\deps\google-play-services_lib\AndroidManifest.xml (The system cannot find the file specified)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.android.io.FileWrapper.getContents(FileWrapper.java:91)
    ... 24 more

Total time: 0 seconds
Build halted with errors.

**Comment by fbricker** [comment]
I'm closing this issue since looks the same reported here: https://github.com/SempaiGames/extension-googleplaygames/issues/15
