### ISSUE TITLE
crash at runtime on android

### ISSUE THREAD

**Issue by ramsestom** [SempaiGames/extension-multigames#6]
At first launch on android, my app asked me to update google play service and google play games on my device to acess leaderboard, wich I did. Then, I relaunched the app but it sytematicaly crash when I try to open a leaderbord with this error:
E/AndroidRuntime(24550): FATAL EXCEPTION: main
E/AndroidRuntime(24550): java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
E/AndroidRuntime(24550):        at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
E/AndroidRuntime(24550):        at com.google.android.gms.common.internal.zzj$zza.zzv(Unknown Source)
E/AndroidRuntime(24550):        at com.google.android.gms.common.internal.zzj$zzc.zzqx(Unknown Source)
E/AndroidRuntime(24550):        at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
E/AndroidRuntime(24550):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24550):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(24550):        at android.app.ActivityThread.main(ActivityThread.java:4777)
E/AndroidRuntime(24550):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24550):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(24550):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(24550):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(24550):        at dalvik.system.NativeStart.main(Native Method)

I compiled this app in legacy mode with latest versions of openfl and lime

EDIT:
I tested directly with extension-googleplaygames rather than using extension-multigames and the strange thing is that it works when using  extension-googleplaygames.... 
When using extension-multigames I have some messages in my arb logs that says:
E/ValidateServiceOp(13912): Application ID (null) must be a numeric value. Please verify that your manifest refers to the correct project ID.
but the process numper is different from the one of my app so not sure it is actually related to the openfl app tested. Anyway, the difference between extension-googleplaygames and extension-multigames is that with extension-googleplaygames the app ID is defined by a `<setenv name="GOOGLE_PLAY_GAMES_ID" value="xxxxxxxxxx" />` tag in my project.xml file whereas with 
extension-multigames I defined it with:
`Multigames.loadResourcesFromXML('<resources>
                                            <string name="app_id">xxxxxxxxxx</string>
                                           </resources>');`
So might be the problem. maybe the app_id from loadResourcesFromXML is not correctly parsed?

EDIT2: It works if I use  `<setenv name="GOOGLE_PLAY_GAMES_ID" value="xxxxxxxxxx" />` with extension-multigames too. So maybe you should modify the README file from extension-multigames because currently it looks like you only need to pass the app id as a xml tag parametter to the loadResourcesFromXML() function which is not the case (it would crash if you don't have it defined with the  GOOGLE_PLAY_GAMES_ID tag in project.xml)
The extension-googleplaygames and extension-multigames still have an issue though. even if defining the app ID with the setenv tag prevent the app to crash, when trying to open a leaderboard, I have a google play games connection popup that appear, then a "spining whell" and... nothing, the leaderboard windows never appear....

**Comment by fbricker** [comment]
Hi, I've added the need to set the GOOGLE_PLAY_GAMES_ID env. var to the project.xml in the readme.

About the issue, I think you may need to check how are you including the extension. Seeing this both errors, I'm quite sure you're including both google play games extensions at the same time (extension-googleplaygames and extension-gpgrest). Try to avoid that (use extension-googleplaygames on android and extension-gpgrest on the rest of the platforms).

PS: One extra detail. If you just want to use google play games (not amazon game circle o apple game-center), then you don't need to use extension-multigames, as both google play games exgtension are API-compatible, so you can just do something like this:

``` xml
<setenv name="GOOGLE_PLAY_GAMES_ID" value="xxxxxxxxxx" />
<haxelib name="extension-googleplaygames" if="android" />
<haxelib name="extension-gpgrest" unless="android" />
```

And then import and use extension.gpg.GooglePlayGames around your project.
